### ISSUE TITLE
Minor code change for watermark in Wagtail 4.1.1

### ISSUE THREAD

**Issue by jbaack** [octavenz/wagtail-snippets#2]
Thanks for the watermark code. In Wagtail 4.1.1 I found it did not work (silently) until I changed 

class WatermarkedOperation(Operation):
to
class WatermarkedOperation(FilterOperation):

and obviously changed the import correspondingly

**Comment by campenr** [comment]
Good find! Addressed with https://github.com/octavenz/wagtail-snippets/commit/e193c47739eb21a2751e9691c66021e563b7150a

Thanks :+1:
